# Generated by Django 4.2.7 on 2025-11-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='additional_information',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_and_culture',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='career_area',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='contractual_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='pay',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='security_vetting',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='shift_work',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='term_of_employment',
            field=models.CharField(default='Permanent', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='the_opportunity',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='what_youll_be_doing',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='who_you_are',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='your_work_location',
            field=models.TextField(default=''),
        ),
    ]
