# Generated by Django 4.2.7 on 2025-11-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_add_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('interested', 'I am Interested'), ('referral', 'Refer a Friend')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('friend_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('friend_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('friend_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('friend_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='careers.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
