# Generated by Django 5.0.1 on 2026-01-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Neeraali Digital', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='how_to_apply',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='working_days_timings',
            field=models.CharField(default='', max_length=200),
        ),
    ]
