# Generated by Django 5.0.1 on 2026-01-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_job_company_job_how_to_apply_job_responsibilities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='job',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='job',
            name='benefits_and_culture',
        ),
        migrations.RemoveField(
            model_name='job',
            name='career_area',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contractual_location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='department',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='job',
            name='remote_work_available',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='job',
            name='security_vetting',
        ),
        migrations.RemoveField(
            model_name='job',
            name='shift_work',
        ),
        migrations.RemoveField(
            model_name='job',
            name='term_of_employment',
        ),
        migrations.RemoveField(
            model_name='job',
            name='the_opportunity',
        ),
        migrations.RemoveField(
            model_name='job',
            name='what_youll_be_doing',
        ),
        migrations.RemoveField(
            model_name='job',
            name='who_you_are',
        ),
        migrations.RemoveField(
            model_name='job',
            name='your_work_location',
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Bengaluru (On-site)', max_length=100),
        ),
    ]
