# Generated by Django 5.0.1 on 2026-01-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_remove_job_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='how_to_apply',
            field=models.TextField(blank=True, default=''),
        ),
    ]
