# Generated by Django 4.2.7 on 2025-11-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='faq_section',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_section',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='services_section',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
