# Generated by Django 4.2.7 on 2025-11-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='related_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
