# Generated by Django 4.2.7 on 2025-11-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_related_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.PositiveIntegerField(default=5, help_text='Estimated read time in minutes'),
        ),
    ]
