# Generated by Django 4.2.7 on 2025-11-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('general', 'General Enquiry'), ('web_analysis', 'Web Analysis')], default='general', max_length=20),
        ),
    ]
